# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sapient < Formula
  desc "Sapient Public API: Public API for Sapient CLI and external integrations."
  homepage "https://github.com/usesapient/cli"
  version "0.4.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/usesapient/cli/releases/download/v0.4.2/cli_Darwin_x86_64.tar.gz"
      sha256 "fbec850b4d8d5eecee4dd206b173a39bdd56c3a1c5e5395756d7ff4d7a43636e"

      define_method(:install) do
        bin.install "sapient"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/usesapient/cli/releases/download/v0.4.2/cli_Darwin_arm64.tar.gz"
      sha256 "197e677529764c4f606d2d0549bb2f413ef1f4cad9af228d94d47b215bcbf2ab"

      define_method(:install) do
        bin.install "sapient"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/usesapient/cli/releases/download/v0.4.2/cli_Linux_x86_64.tar.gz"
      sha256 "22b19d195cc1aeb0ab1f4ca61e9c716eb4560e6eb52272cb157eba48dd437768"
      define_method(:install) do
        bin.install "sapient"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/usesapient/cli/releases/download/v0.4.2/cli_Linux_arm64.tar.gz"
      sha256 "c7a0f484b91f1114f53b033d578c7d528ef9445db7d48000608058ecc61a6404"
      define_method(:install) do
        bin.install "sapient"
      end
    end
  end
end
