# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lightsage < Formula
  desc "Manage Lightsage visibility, prompts, evals, content, and tasks"
  homepage "https://lightsage.com/docs"
  version "0.7.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lightsagehq/homebrew-tools/releases/download/v0.7.3/lightsage_Darwin_x86_64.tar.gz"
      sha256 "0aa80ca6ea860dd2dbbbaee1fec0142d7b1c88029e610ddb956f9b556b125bb5"

      def install
        bin.install "lightsage"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lightsagehq/homebrew-tools/releases/download/v0.7.3/lightsage_Darwin_arm64.tar.gz"
      sha256 "9bd29911e8f93382f07bdfd0e56c5fa9dc49f31133a9e55e82e8620df684234b"

      def install
        bin.install "lightsage"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/lightsagehq/homebrew-tools/releases/download/v0.7.3/lightsage_Linux_x86_64.tar.gz"
      sha256 "1929af3d633c7a97087ae705f2351836f838af4fa25c6158358cd18519fc4db0"
      def install
        bin.install "lightsage"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/lightsagehq/homebrew-tools/releases/download/v0.7.3/lightsage_Linux_arm64.tar.gz"
      sha256 "34ecf142909a79b91f76ec7c87dc9b8c29f4f01f86bbe876b0da2bb2fc8f76f7"
      def install
        bin.install "lightsage"
      end
    end
  end

  test do
    system "#{bin}/lightsage", "version"
  end
end
