# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sapient < Formula
  desc "Sapient Public API: Public API for Sapient CLI and external integrations."
  homepage "https://github.com/usesapient/cli"
  version "0.4.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/usesapient/cli/releases/download/v0.4.4/cli_Darwin_x86_64.tar.gz"
      sha256 "6fd0e0c942ba5e7da5b372cd39c57f1ac171470837cbdef5f2480f5061e33fee"

      define_method(:install) do
        bin.install "sapient"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/usesapient/cli/releases/download/v0.4.4/cli_Darwin_arm64.tar.gz"
      sha256 "37f9156b03d337c78772d0fea2e3748e6b6783337b43b706489ffb853018d326"

      define_method(:install) do
        bin.install "sapient"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/usesapient/cli/releases/download/v0.4.4/cli_Linux_x86_64.tar.gz"
      sha256 "891266416e5c904de1ad49ef4c2dcf0aabd491bae7394e81a5218f519d32f740"
      define_method(:install) do
        bin.install "sapient"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/usesapient/cli/releases/download/v0.4.4/cli_Linux_arm64.tar.gz"
      sha256 "9c493fdba95bc3c4c8495c99118cc49a6f60fa3ec2a78457a3bf43262261c70d"
      define_method(:install) do
        bin.install "sapient"
      end
    end
  end

  test do
    system "#{bin}/sapient", "version"
  end
end
