# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sapient < Formula
  desc "The official CLI for Sapient."
  homepage "https://docs.usesapient.com"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/usesapient/sapient-cli/releases/download/v0.1.0/sapient_0.1.0_macos_amd64.zip"
      sha256 "54950783a7c1d656def2843f8f69ba48b008e8bad2e530971ce3a25dba9a8176"

      define_method(:install) do
        bin.install "sapient"
        bash_completion.install "completions/sapient.bash" => "sapient"
        zsh_completion.install "completions/sapient.zsh" => "_sapient"
        fish_completion.install "completions/sapient.fish"
        man1.install Dir["man/man1/*.1.gz"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/usesapient/sapient-cli/releases/download/v0.1.0/sapient_0.1.0_macos_arm64.zip"
      sha256 "8415882a14aa3e7ee37c9e71b790473d4b4a9da7d23c6fb32eae37597110a72d"

      define_method(:install) do
        bin.install "sapient"
        bash_completion.install "completions/sapient.bash" => "sapient"
        zsh_completion.install "completions/sapient.zsh" => "_sapient"
        fish_completion.install "completions/sapient.fish"
        man1.install Dir["man/man1/*.1.gz"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/usesapient/sapient-cli/releases/download/v0.1.0/sapient_0.1.0_linux_amd64.tar.gz"
      sha256 "d1ce708bc9eeecc1ad55972fedbb27766ab0c404530689e13b5835f4a58e31a1"
      define_method(:install) do
        bin.install "sapient"
        bash_completion.install "completions/sapient.bash" => "sapient"
        zsh_completion.install "completions/sapient.zsh" => "_sapient"
        fish_completion.install "completions/sapient.fish"
        man1.install Dir["man/man1/*.1.gz"]
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/usesapient/sapient-cli/releases/download/v0.1.0/sapient_0.1.0_linux_armv6.tar.gz"
      sha256 "91316b7ac3ee0a0f7ab54d52f23f2f3476f1783e36beb7f56f24deac638b2f40"
      define_method(:install) do
        bin.install "sapient"
        bash_completion.install "completions/sapient.bash" => "sapient"
        zsh_completion.install "completions/sapient.zsh" => "_sapient"
        fish_completion.install "completions/sapient.fish"
        man1.install Dir["man/man1/*.1.gz"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/usesapient/sapient-cli/releases/download/v0.1.0/sapient_0.1.0_linux_arm64.tar.gz"
      sha256 "987d7b6d448bb643cbd6d633574e3b89152f3ae26ec4994a7321ad3109ecdbea"
      define_method(:install) do
        bin.install "sapient"
        bash_completion.install "completions/sapient.bash" => "sapient"
        zsh_completion.install "completions/sapient.zsh" => "_sapient"
        fish_completion.install "completions/sapient.fish"
        man1.install Dir["man/man1/*.1.gz"]
      end
    end
  end

  test do
    system "#{bin}/sapient", "--version"
  end
end
